### ISSUE TITLE
Node version requirements

### ISSUE THREAD

**Issue by JonoSuave** [smeijer/spin-delay#12]
Does this require node version greater than or equal to 18? I received the following error when I tried to do a yarn add spin-delay:
```
error @azure/logger@1.1.2: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.2"
error Found incompatible module.
```

**Comment by smeijer** [comment]
> "error @azure/logger@1.1.2:"

Wrong repo? We only have a peer dependency on react, so I don't think that error is ours.
