### ISSUE TITLE
Delay is always ignored on mount (defeating the purpose of delay)

### ISSUE THREAD

**Issue by evanzieg** [smeijer/spin-delay#13]
The `useIsSSR` hook is hardcoded to always return true when the component mounts, which isn't the worst assumption given the state of the React ecosystem. 

However, the `ssr` option is not considered when deciding if the `delay` option should be respected or not. 

![image](https://github.com/smeijer/spin-delay/assets/60709447/9b6d327d-dbb2-4f37-ab71-7a4067348f42)

This means that the spinner will always show immediately unless you are also using the `loading` prop you pass in as a backup like the setup below:

![image](https://github.com/smeijer/spin-delay/assets/60709447/2fe4e2d4-d1b2-4492-8e4d-cd8df1f8a8bb)

## Steps to reproduce
1. Have the following:
   * Use `useSpinDelay` in a component and ensure the `options` argument at least has `{ delay: <some value>, ssr: false }`
   * A `loading` useState that will start `false` and is passed as the `loading` argument to `useSpinDelay`
   * A button that will set `loading` to `true`, and then adds a timeout for a period of time that will set `loading` back to `false`
   * A span/div/etc. that shows the state of `loading` for verification
2. Ensure the timeout to set `loading` to false is relatively short (<1 sec) and the `delay` option is longer (1-2 sec)
3. Click the button

### Expected behavior
The loading spinner will not show and the loading verification will show `true` then `false`.

### Actual behavior
The loading spinner appears immediately and will hide when `loading` gets set back to `false`
If the `minDuration` option is specified, then the spinner will appear for only the full length of the `minDuration`, not including the `delay` amount.

---
Unrelated: the code sandbox in the README is really useful! However, it is still using version 0.0.1 by default, which means it doesn't show off the current behaviors properly.

**Comment by evanzieg** [comment]
Update: on further inspection, it looks like this was fixed by #9 a couple months ago. However, the package was not updated/published so it is still broken when downloading from npm.

**Comment by smeijer** [comment]
Yeah, sorry. Need to write a changeset, and merge that.

**Comment by smeijer** [comment]
The package is updated and [`v2.0.1`](https://github.com/smeijer/spin-delay/releases/tag/v2.0.1) includes #9. Sorry, it took me so long.
